language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

# run build against hhvm but allow them to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
    - php: 7.0

before_script:
  - sh .travis.install.sh
  - composer install

script: phpunit --configuration tests/phpunit.xml
