language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

# run build against hhvm but allow them to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  fast_finish: true
  allow_failures:

before_script:
  - sh .travis.install.sh
  - composer install

script: phpunit --configuration tests/phpunit.xml
